export enum JobStatus {
  PENDING = 'PENDING',
  APPLIED = 'APPLIED',
  NO_RESPONSE = 'NO_RESPONSE',
  TECHNICAL_TEST = 'TECHNICAL_TEST',
  INTERVIEW = 'INTERVIEW',
  OFFER = 'OFFER',
  REJECTED = 'REJECTED',
}
